name: Deploy
on:
  push:
    branches:
      - test
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: 'Rodcarm/personal-website' # Correct repository reference
          token: ${{ secrets.API_TOKEN_GITHUB }}
          ref: main
          fetch-depth: 0 
          
      - name: Set up Git Configuration
        run: |
          git config --global user.name "Rodrigo"
          git config --global user.email "rcarmona@realmetrics.io"
      - name: Git status
        run: |
          git status
      - name: Push to gitAccionTest
        run: |
          git push --force https://${{ secrets.API_TOKEN_GITHUB }}@github.com/Rodcarm/gitActionspersonal-website.git