name: Deploy
on:
  push:
    branches:
      - test
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: 'Rodcarm/personal-website'
          token: ${{ secrets.API_TOKEN_GITHUB }}
          ref: main
          fetch-depth: 0 
          
      - name: Set up Git Configuration
        run: |
          git config --global user.name "Rodrigo"
          git config --global user.email "rcarmona@realmetrics.io"
      - name: Git status
        run: |
          git status
      - name: Push to gitAccionTest
        run: |
          git push --force https://${{ secrets.API_TOKEN_GITHUB }}@github.com/Rodcarm/gitActionspersonal-website.git

# name: Deploy
# on:
#   push:
#     branches:
#       - main
# jobs:
#   file-update-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Push file
#         uses: nkoppel/push-files-to-another-repository@v1.1.3
#         env:
#           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#         with:
#           source-files: './webpersonal/core/views.py'
#           destination-branch: 'main'
#           destination-username: 'Rodcarm'
#           destination-repository: 'gitActionspersonal-website'
#           destination-directory: 'webpersonal/core'
#           commit-email: rcarmona@realmetrics.io