# name: Run File Changes
# on:
#   push:
#     branches:
#       - main
#     # paths:
#     #   - 'archivesToTest.txt'
#       #- 'webpersonal/core/views.py'
# jobs:
#   file-update-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Push file to another repository
#         uses: nkoppel/push-files-to-another-repository@v1.1.3
#         env:
#           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#         with:
#           source-files: './files/new-files/archivesToTest.txt'
#           destination-branch: 'main'
#           destination-username: 'Rodcarm'
#           destination-repository: 'controller'
#           destination-directory: 'files/new-files/test.txt'
#           commit-email: rcarmona@realmetrics.io

name: Run File Changes Json
on:
  push:
    branches:
      - main
    # paths:
    #   - 'deploy.json'
jobs:
  file-update-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Get Var
        run: |
          paths=$(jq -r ".paths[]" deploy.json)
          commit-message=$(jq -r ".commit-message" deploy.json)
          echo "${paths}"
          echo "${commit-message}"
