name: Run File Changes
on:
  push:
    branches:
      - main
    # paths:
    #   - 'archivesToTest.txt'
      #- 'webpersonal/core/views.py'
jobs:
  file-update-job:
    runs-on: ubuntu-latest
    steps:
      - name: Push file to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: './archivesToTest.txt'
          destination-username: 'Rodcarm'
          destination-repository: 'controller'
          destination-directory: 'files/new-files'
          commit-email: rcarmona@realmetrics.io
      # - name: Get main repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'Rodcarm/personal-website'
      #     token: ${{ secrets.API_TOKEN_GITHUB }}
      # - name: Get controller repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'Rodcarm/controller'
      #     token: ${{ secrets.API_TOKEN_GITHUB }}
      # - name: Checkout code
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'Rodcarm/personal-website' # Correct repository reference
      #     token: ${{ secrets.API_TOKEN_GITHUB }}
      #     ref: main
      #     fetch-depth: 0
      # - name: Set up Git Configuration
      #   run: |
      #     git config --global user.name "Rodrigo"
      #     git config --global user.email "rcarmona@realmetrics.io"
      # - name: Print each line of the text
      #   run: |
      #     if [[ -f archivesToTest.txt ]]; then
      #       while IFS= read -r line || [[ -n "$line" ]]; do
      #         echo "$line"
      #         git add "$line"
      #       done < archivesToTest.txt
      #     else
      #       echo "El archivo archivesToTest.txt no existe"
      #     fi
      # - name: Gitstatus
      #   run: |
      #     git status
      # - name: Run script
      #   run: echo "El archivo fue modificado"