name: Run File Changes
on:
  push:
    branches:
      - main
    # paths:
    #   - 'archivesToTest.txt'
      #- 'webpersonal/core/views.py'
jobs:
  file-update-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print each line of the text
        run: |
          if [[ -f archivesToTest.txt ]]; then
            while IFS= read -r line || [[ -n "$line" ]]; do
              echo "$line"
            done < archivesToTest.txt
          else
            echo "El archivo archivesToTest.txt no existe"
          fi
      - name: GitStatus
        run: |
          git status
      - name: Run script
        run: echo "El archivo fue modificado"