name: Run File Changes Json
on:
  push:
    branches:
      - main
jobs:
  file-update-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Var
        run: |
          paths=$(jq -r ".paths[]" files/new-files/deploy.json)
          echo "${paths}"
          commit_message=$(jq -r ".commit_message" files/new-files/deploy.json)
          echo "${commit_message}"
          echo "${{ github.actor }}"
          echo ${{ github.event.head_commit.author.email }}
      # - name: Push file to another repository
      #   uses: nkoppel/push-files-to-another-repository@v1.1.3
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source-files: './files/new-files/archivesToTest.txt'
      #     destination-branch: 'main'
      #     destination-username: 'Rodcarm'
      #     destination-repository: 'controller'
      #     destination-directory: 'files/new-files/test.txt'
      #     commit-email: rcarmona@realmetrics.io
