name: Run File Changes Json
on:
  push:
    branches:
      - main
    paths:
      - 'files/new-files/deploy.json'
jobs:
  file-update-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Var
        run: |
          commit_message=$(jq -r ".commit_message" files/new-files/deploy.json)
          echo "commit_message=${commit_message}" >> $GITHUB_ENV
          echo "USER_COMMIT=${{ github.actor }}" >> $GITHUB_ENV
          echo "EMAIL=${{ github.event.head_commit.author.email }}" >> $GITHUB_ENV
          
      - name: print Var
        run: |
          echo "${commit_message}"
          echo "${USER_COMMIT}"
          echo ${EMAIL}
      - name: Push file to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          USER_COMMIT: ${{ env.USER_COMMIT }} 
          EMAIL: ${{ env.EMAIL }}
          COMMIT_MESSAGE: ${{ env.commit_message }}
        with:
          source-files: './files/new-files/archivesToTest.txt'
          destination-branch: 'main'
          destination-username: 'Rodcarm'
          destination-repository: 'controller'
          destination-directory: 'files/new-files/'
          commit-email: "${{ env.USER_COMMIT }}"
          commit-username: "${{ env.EMAIL }}"
          commit-message: "${{ env.commit_message }}"
