name: Run File Changes
on:
  push:
    branches:
      - main
    # paths:
    #   - 'archivesToTest.txt'
      #- 'webpersonal/core/views.py'
jobs:
  file-update-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print each line of the text
        run: |
          while IFS= read -r line; 
          do
            echo "$line"
          done < ./archivesToTest.txt
      - name: read txt
        run: |
          data= `cat ./archivesToTest.txt`
          echo "$data"
      - name: Run script
        run: echo "El archivo fue modificado"