name: Run File Changes Json
on:
  push:
    branches:
      - main
jobs:
  file-update-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Get Var
        run: |
          paths=$(jq -r ".paths[]" ./files/new-files/deploy.json)
          commit-message=$(jq -r ".commit-message" ./files/new-files/deploy.json)
          echo "${paths}"
          echo "${commit-message}"
